import { ROLE } from "./role";

export const ACCESS = {
	AUTH: [ROLE.ADMIN, ROLE.EDITOR, ROLE.SELLER_ONLINE, ROLE.SELLER_ON_STORE, ROLE.USER],
	CATALOG: [ROLE.ADMIN, ROLE.EDITOR, ROLE.SELLER_ONLINE, ROLE.SELLER_ON_STORE],
	WATCH_PRODUCTS: [ROLE.ADMIN, ROLE.EDITOR, ROLE.SELLER_ONLINE, ROLE.SELLER_ON_STORE],
	EDIT_PRODUCTS: [ROLE.ADMIN, ROLE.EDITOR, ROLE.SELLER_ONLINE],
	DELETE_PRODUCTS: [ROLE.ADMIN, ROLE.EDITOR, ROLE.SELLER_ONLINE],

	USERS: [ROLE.ADMIN],
	LOGS: [ROLE.ADMIN, ROLE.EDITOR],

}
