const PHOTOS_TYPE = require("./photos-type");

const PHOTOS_URLS = {
  HOME_FOLDER: "photos",
  PRODUCTS_FOLDER: "products",
  MEASUREMENTS_FOLDER: PHOTOS_TYPE.TYPE_MEASUREMENTS,
  COVER_FOLDER: PHOTOS_TYPE.TYPE_COVER,
};

module.exports = PHOTOS_URLS;
